version: "3.9"

services:
  api:
    build: .
    container_name: pdef-generator-3-api
    ports:
      - "80:80"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
